### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by yckart** [jquery-boilerplate/jqueryboilerplate.com#8]

**Comment by zenorocha** [comment]
I agree, we need to improve it.

I think we can also include those @addyosmani's  [patterns](https://github.com/jquery-boilerplate/website/issues/8) on this new website.

We just need a designer now =/

**Comment by yckart** [comment]
I'm busy until next week, thereafter I am free and can spend a bit of my time on it.

**Comment by zenorocha** [comment]
That would be great!

**Comment by zenorocha** [comment]
Done: http://jqueryboilerplate.com
